1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.77231433 0.26938019 0.60420054]
  [0.82814995 0.20177697 0.10212764]
  [0.66045859 0.78868194 0.60352851]]

 [[0.61201549 0.09374741 0.4735057 ]
  [0.23737188 0.46683792 0.45405212]
  [0.75303671 0.29798129 0.46034882]]

 [[0.7259647  0.98033521 0.28735692]
  [0.80097252 0.3631758  0.15618879]
  [0.52373488 0.44367652 0.73803502]]]


2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal"

In [13]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [16]:
import numpy as np
x1 = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 4. Normalize a 5x5 random matrix

In [18]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.99026373 -0.87840529 -0.4546855   1.49602326  1.95575478]
 [-0.06665296 -0.6958618  -1.05499397 -0.40405798  0.92111571]
 [-0.51669139 -0.91372986 -0.10183477  1.52915934 -0.46004438]
 [-0.63811294 -0.85597399 -0.71425166  1.19001915  0.27131006]
 [-1.57629322  0.82215908 -0.92699063  0.56991046 -0.48713524]]


 5.  How to find common values between two arrays?

In [22]:
Z1 = np.array([1,2,3,4])
Z2 = np.array([3,4,5,6])

print(np.intersect1d(Z1,Z2))

[3 4]


6.How to get the dates of yesterday, today and tomorrow?

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(2, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')


numpy.datetime64('2020-07-26')

In [34]:
today

numpy.datetime64('2020-07-25')

In [37]:
yesterday

numpy.datetime64('2020-07-24')

In [36]:
tomorrow

numpy.datetime64('2020-07-26')

In [38]:
yesterday

numpy.datetime64('2020-07-24')

 7. Consider two random array A and B, check if they are equal

In [50]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


8.Create random vector of size 10 and replace the maximum value by 0

In [53]:
Z = np.random.random(10)
Z

array([0.66605459, 0.86230967, 0.97934227, 0.97197705, 0.16664103,
       0.9058633 , 0.04605226, 0.37619226, 0.06169098, 0.94178879])

In [58]:
Z[Z.argmax()] = 0
print(Z)

[0.66605459 0.86230967 0.         0.         0.16664103 0.9058633
 0.04605226 0.37619226 0.06169098 0.94178879]


9. How to print all the values of an array?

In [65]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((20,20))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

10.Subtract the mean of each row of a matrix

In [68]:
X = np.random.rand(5, 5)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.24064382 -0.17803421  0.46640529  0.27312578 -0.32085304]
 [ 0.11656046  0.3493503  -0.2897532  -0.26471074  0.08855317]
 [-0.21272374 -0.26673532  0.25705359  0.09003138  0.13237409]
 [ 0.40008073  0.00816658  0.09552048 -0.17482987 -0.32893793]
 [-0.0494036   0.41613099 -0.24403197 -0.10109485 -0.02160058]]


11.Consider a given vector, how to add 1 to each element indexed by a second vector

In [70]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
I

array([9, 4, 1, 0, 8, 7, 1, 6, 9, 9, 0, 6, 9, 0, 3, 6, 4, 1, 5, 0])

In [72]:
np.add.at(Z, I, 1)
print(Z)

[5. 4. 1. 2. 3. 2. 4. 2. 2. 5.]


12.How to get the diagonal of a dot product?

In [77]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

  
np.diag(np.dot(A, B))

array([1.05486194, 0.54441692, 0.90598391, 1.27177334, 2.00895071])

In [74]:
A

array([[0.53216819, 0.80310323, 0.30378553, 0.01716316, 0.97563198],
       [0.99986185, 0.65569856, 0.64726547, 0.09371576, 0.34873815],
       [0.75533491, 0.35845466, 0.97797085, 0.71260215, 0.46834245],
       [0.01820781, 0.09222042, 0.15873198, 0.17101652, 0.29458877],
       [0.32658915, 0.20101867, 0.77526253, 0.26267973, 0.31114427]])

In [78]:
B

array([[0.84519186, 0.02793878, 0.34519442, 0.88492146, 0.30866063],
       [0.62239011, 0.19290176, 0.22256053, 0.1074137 , 0.75802413],
       [0.71450262, 0.06542959, 0.13230537, 0.22592112, 0.57051844],
       [0.83268792, 0.79472835, 0.83626217, 0.47189514, 0.91416917],
       [0.41377056, 0.69981042, 0.20547623, 0.03445879, 0.40799772]])

In [79]:
np.dot(A,B)

array([[1.05486194, 0.32238392, 0.41644476, 0.5158986 , 0.89068972],
       [0.87250405, 0.54441692, 0.56474942, 0.4295607 , 0.85613412],
       [1.2054185 , 0.8536543 , 0.90598391, 0.71718807, 1.11585621],
       [2.56038128, 1.10118927, 1.01353467, 1.27177334, 2.03761908],
       [2.46953535, 1.30921895, 1.33763682, 1.42667455, 2.00895071]])

13.How to find the most frequent value in an array?

In [83]:
Z = np.random.randint(0,10,50)
Z

array([5, 2, 3, 9, 1, 4, 8, 5, 1, 0, 2, 5, 8, 0, 1, 8, 0, 1, 7, 9, 9, 9,
       1, 6, 6, 4, 5, 2, 3, 5, 0, 2, 6, 2, 0, 2, 3, 3, 7, 0, 6, 8, 6, 2,
       1, 1, 2, 2, 5, 3])

In [88]:
print(np.bincount(Z).argmax())

2


14.How to get the n largest values of an array

In [89]:
Z = np.arange(10000)
s=np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [90]:
s

array([1, 2, 4, 0, 3])

15.How to create a record array from a regular array?

In [91]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
